version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 99
  labels:
  - automatic
  - dependencies
  allow:
  - dependency-type: direct
  - dependency-type: indirect
