# These are supported funding model platforms

patreon: PROgrm_JARvis
open_collective: # Replace with a single Open Collective username
ko_fi: PROgrm_JARvis
custom:
  - http://qiwi.com/n/PROgrammerJARvis
  - https://yoomoney.ru/to/410013423232443
