pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot\[bot\]$
      # Note: no need for `checks-success=...` thanks to branch protection rules
    actions:
      merge:
        method: merge
        strict: smart+fasttrack
      # Note: no need for `delete_head_branch: {}`
      # as it is done by dependabot itself
