# Specify primary repository language
language: rust

# Boost build by caching dependencies
# see: https://docs.travis-ci.com/user/languages/rust/#dependency-management
cache: cargo

# Install all Rust channels to test against experimental ones
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  # Install rustfmt and clippy to use them for code verification
  - rustup component add rustfmt clippy

# Main script to be used for verification
script:
  - cargo build --workspace
  - cargo test --workspace
  - cargo fmt -- --check
  - >-
    cargo clippy --all-targets --all-features
    -- -W clippy::all -W clippy::pedantic -W clippy::restriction -W clippy::nursery -D warnings
